ustclug/ustcmirror-images

homebrew-bottles/sync.sh
to prevent some undefined behavior, like network temporarily failed.
=> homebrew-bottles: set -e

lftpsync/sync.sh
对于不以/结尾的目录（HTTP协议），如果开启--skip-no-access，lftp会跳过这些目录。
如果确实需要--skip-noaccess参数，可以针对特定源开启该选项，不建议作为公共必选参数。
=> lftp: drop `--skip-noaccess` parameter. (fix #31)

hackage/sync.sh
=> update hackage: use 01-index.tar.gz

fedora/pre-sync.sh
```
rsync: do_fallocate "/mirror/fedora-secondary/updates/26/i386/Packages/m/meshlab-2016.12-6.fc26.i686.rpm": Not supported (95)
```
=> fix(fedora): remove --preallocate

README.md, aptsync/Dockerfile, aptsync/pre-sync.sh
对于部分上游地址（如`http://packages.ros.org/ros/ubuntu`）， 假设 `TO=/srv/repo/ros`，则最终目录结构为 `/srv/repo/ros/ros/ubuntu`。这显然不是我们需要的。
作为workaround，可以配置 `TO=/srv/repo`，但这会损失docker带来的隔离特性。
该PR增加了一个变量`APTSYNC_CREATE_DIR`，用以改变自动创建目录的行为。为了与旧版本相兼容，默认值为 `true`。
link: https://github.com/ustclug/mirrorrequest/issues/195
=> feat(aptsync): env APTSYNC_CREATE_DIR

README.md, julia/Dockerfile, julia/sync.sh
This uses the [`julia-mirror` scripts](https://github.com/sunoru/julia-mirror) to download the Julia ecosystem (Julia versions, Julia packages, etc...) to `/data` within the docker container, outputting logs into `/logs`.
=> Use `julia-mirror` to mirror Julia ecosystem

base/Dockerfile.centos, fedora/Dockerfile, freebsd-pkg/sync.sh, freebsd-ports/sync-ports.sh
在用到 curl 的地方都加上了 `--fail`，防止下载下来的是一个 html 文件
=> fix: pass --fail to curl in case of server errors

configure.py, homebrew-bottles/Dockerfile, rsync/Dockerfile
* 现在 `configure.py` 在读 Dockerfile 的时候会从后往前读，把读到的第一个 `FROM` 指令后的 image 作为 base image
* 顺便去掉了 `configure.py` 里读取环境变量 `TRAVIS_COMMIT_RANGE` 的逻辑
=> 让 configure.py 可以正确处理使用了 multi-stage build 的 Dockerfile

apt-sync/Dockerfile, apt-sync/sync.py, apt-sync/sync.sh
Motivation:
Originally attempted to trim whitespaces around each `APTSYNC_DIST` item to allow saner configuration. For example, our conf for Termux is currently:
```yaml
envs:
APTSYNC_DISTS: stable|main|aarch64 all arm i686 x86_64|k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx:unstable|main|aarch64 all arm i686 x86_64|k51qzi5uqu5dj05z8mr958kwvrg7a0wqouj5nnoo5uqu1btnsljvpznfaav9nk:x11|main|aarch64 arm i686 x86_64|k51qzi5uqu5dgu3homski160l4t4bmp52vb6dbgxb5bda90rewnwg64wnkwxj4:science|stable|aarch64 all arm i686 x86_64|k51qzi5uqu5dhvbtvdf46kkhobzgamhiirte6s6k28l2c1iapumphh3cpkw33f:games|stable|aarch64 arm i686 x86_64|k51qzi5uqu5dhngjg68o8x9uimwy5h8iqt91n2266idc7uet9ew3lc472upy27:root|stable|aarch64 arm i686 x86_64|k51qzi5uqu5dlp5yjlahzcp3kfpnhbifo9ka9iybo3bp5vt781duafkyyvt9al …
```
=> Replace shell script with Python

README.md, base/Dockerfile.alpine-3.6, docker-ce/Dockerfile, docker-ce/LICENSE, docker-ce/sync.sh, docker-ce/tunasync/sync.py, lftpsync/Dockerfile.alpine-3.6
修改自 `https://github.com/tuna/tunasync-scripts/blob/master/docker-ce.py`，增加了软链接处理的部分，并且把 Alpine 3.6 的 base image 删掉了（因为不再需要那一个版本的 lftp 了）。
主要原因是发现 lftp 对修改时间的处理可能有问题（mirrors2 总是会把所有文件都同步一遍），再加上只有旧版本的 lftp 才能正确同步 docker-ce 的内容，所以不如搞个脚本来处理，顺便软链接正确处理后可以节约一小部分的磁盘空间。
Fix #61.
=> Add docker-ce syncing script

README.md, crates-io-index/Dockerfile, crates-io-index/sync.sh
将目前使用 crontab 的 crates.io-index 同步任务迁移至能够用 Yuki 管理的 Docker。
=> Migrate crates.io-index sync script to docker

README.md, google-repo/Dockerfile, google-repo/sync.sh
添加了 `google-repo`，用于同步使用 `repo` 工具构建的项目的仓库（目前只有 AOSP）。在本地测试过，看起来是可以用的（AOSP 太大了，不能跑完整同步测试）。
=> Migrate AOSP sync script to docker

README.md, lftpsync/sync.sh
In our project we need to upload logs to sftp over ssh and use custom key to login to remote SSH server. It is currently not possible to send extra `set` command to lftp, so I have created simple patch to enable it. User can easily add env variable LFTPSYNC_EXTRA_SET in docker-compose with one or more custom sets and it will be placet before mirror command.
=> add support for extra settings in lftp

winget-source/package-lock.json, winget-source/package.json, winget-source/utilities.js
为 `winget-source` 工具引入 HTTP 请求重试功能，减少网络错误导致的同步失败。
=> winget-source: add retry support for `fetch`

winget-source/sync-repo.js, winget-source/utilities.js
我们假定所有清单文件不会被更新，因此只需要同步索引和新增的清单。
=> winget-source: adjust sync logic based on stronger assumption

winget-source/sync-repo.js
=> winget-source: fix bug related to `async`

README.md, yukina/Dockerfile, yukina/sync.sh
<https://github.com/taoky/yukina>
作为解决 nix-channels 占用空间巨大（而且还不完整），但是实际使用的内容很少的方案。Yukina 会分析对应时长（现在是 7 天）的 nginx 日志，在给定的大小约束下下载流行的文件，驱逐（删除）不流行的文件。
预期的使用方式是：原先的同步容器仍然运行，但是只同步 index；Nginx 设置对不存在的文件 302 或者 404，并且日志以特定名称输出到特定的目录下。Yukina 运行时（理想情况下，需要相对较高的执行频率）从挂载的日志中读取内容、只对 binary blob 类型的文件（大多数时候需要用户自己写正则 filter 规则）进行操作。
=> Add yukina

winget-source/sync-repo.js, winget-source/utilities.js
Try fixing the issue mentioned in https://github.com/ustclug/discussions/issues/435#issuecomment-2197544426.
cc @stevapple
=> winget-source: rename index file after syncing is done

winget-source/package-lock.json, winget-source/package.json, winget-source/sync-repo.js, winget-source/utilities.js
完全使用 `async/await` 语法重写 `winget-source` 工具，增加 `sync-repo.js` 的可读性。
=> winget-source: migrate from `Promise` to `async/await`

ghcup/ghcupsync.hs
ghcup metadata 在 0.0.7 添加了 vanilla ，
并在 0.0.8 添加了 cross compiler ，
而在原本的 version parser 中并没有支持。
我修改了 parseVersionFromFileName 以添加支持，
同时考虑到未来可能的更多不同 metadata 版本，
实现了向前兼容（但性能更差的） parser 版本。
=> ghcup: support vanilla and cross compilers

freebsd-pkg/sync.sh
增加 FreeBSD 模块源、补充 pkgbase 源。
现在的 base* 源是 stable 分支 pkgbase 更新用的，而 release* 是 release 分支  pkgbase 更新用的。
模块源参见 
- <https://lists.freebsd.org/archives/freebsd-ports/2024-December/006997.html>
- <https://forums.freebsd.org/threads/possible-solution-to-the-drm-kmod-kernel-mismatch-after-upgrade-from-bapt.96058/>
=> freebsd-pkg: Add Kmod

freebsd-ports/sync-ports.sh
Add prefix path `ports/` for tat.gz archive.
=> freebsd-ports: fix the prefix path of tar.gz archive.

ghcup/ghcupsync.hs, ghcup/sync.sh, hackage/sync.sh
During the installation of cabal,
GHCup would update cabal as soon as it's installed;
But at that point, Cabal config is not adjusted to ustcmirror.
We add a logic to addjust cabal config before cabal updating.
我的疑虑是，
这样的对脚本进行的`插入一行命令`式的更新
是否会对可维护性造成破坏
=> Erchiusx ghcup bootstrap cabal
