.gitmodules
README.md
archvsync/.dockerignore
archvsync/.gitignore
archvsync/Dockerfile
archvsync/build.sh
archvsync/pre-sync.sh
archvsync/sync.sh
archvsync/update.patch

Add archvsync

---

.gitmodules
README.md
aptsync/.dockerignore
aptsync/.gitignore
aptsync/Dockerfile
aptsync/build.sh
aptsync/pre-sync.sh
aptsync/sync.sh
aptsync/update.patch

Add aptsync

---

gsutil-rsync/Dockerfile
gsutil-rsync/sync.sh

add gsutil-rsync

---

hackage/Dockerfile
hackage/sync.sh

fix bug: no mktemp

---

README.md
rclone/Dockerfile
rclone/sync.sh

Add rclone

---

README.md

freebsd-ports: add docs

---

nodesource/sync-nodesource.sh

nodejs 9 出来一段时间了，希望更新合并这个 pr 更新版本。
https://deb.nodesource.com/node_9.x/
ci 通过了，应该没有问题。

更新 node 镜像为 9.x 版本 / update node to 9.x version 

---

hackage/sync.sh

fix:avoid duplicated downloads

---

README.md
fedora/Dockerfile
fedora/pre-sync.sh
fedora/sync.sh

feat(fedora): add fedora sync script

---

stackage/stackage.hs

feat(stackage): sync stack from github

---

base/Dockerfile.centos
base/Dockerfile.debian
configure.py

- ~~[ ] 更新 README~~
debian 跟 centos 的 base image 从 ustclug ftp 下载 `su-exec` binary

从 ustclug ftp 下载 su-exec

---

nodesource/sync-nodesource.sh

Add 11.x and 12.x to node source

---

README.md
nix-channels/Dockerfile
nix-channels/nix-channels.py

- Avoid costly xz operation using nix path-info and a parallel downloader
- Add garbage collection
- Update due to upstream change
Synchronized with tuna/tunasync-scripts

nix-channels: Updates

---

nodesource/sync-nodesource.sh

bump node source version to 15.X

nodesource: add 13.x, 14.x, 15.x

---

README.md

更新 README：microbadger 迁移到 shields.io，更新 README License

readme: move to shields.io and format

---

rsync/Dockerfile
rsync/lchmod.c

rsync: supress lchmod error (fix #71)

---

.gitignore
README.md
ghcup/Dockerfile
ghcup/README
ghcup/config
ghcup/ghcupsync.cabal
ghcup/ghcupsync.hs
ghcup/prepare.sh
ghcup/sync.sh

增加 ghcup 同步工具。目前完整同步需要 55GB 空间。
please review

增加 ghcup 同步工具

---

winget-source/Dockerfile
winget-source/sync-repo.js
winget-source/sysexits.js
winget-source/utilities.js

改进 `winget-source` 工具错误处理功能：
- 修复了错误日志获取到 `undefined` 的问题；
- DEBUG 模式下增加 stack trace 记录；
- 引入 BSD 风格的 `sysexits` 错误状态码；
- 引入用于错误退出的 `exitOnError` 高阶函数；
- 增加了若干处自定义错误处理。

winget-source: improve error handling

---

README.md
gitsync/sync.sh

Update gitsync to implement #96.

gitsync: add checkout and treeless option

---

archvsync/Dockerfile
base/Dockerfile.alpine
base/Dockerfile.alpine-3.12
debian-cd/Dockerfile
fedora/Dockerfile
rsync/Dockerfile

Fix #100 
upgrade the base Alpine image to version 3.16

Update Dockerfile.alpine from 3.14 to 3.16

---

winget-source/utilities.js

Fix https://github.com/ustclug/discussions/issues/435.

winget-source: retry also when status >= 400

---

archvsync/update.patch

archvsync: update to 65335777

---

.github/workflows/build.yml
README.md
rsync/sync.sh

Add RSYNC_FILTER for rsync

---

winget-source/package-lock.json
winget-source/package.json
winget-source/sync-repo.js
winget-source/utilities.js

- 更新了 `npm` 软件包版本；
- 额外同步 `source2.msix`；
- 不再产生 `source.msix.tmp` 临时文件；
- 修复了 `source.msix` 时间戳错误的问题；
- 使用标准库函数 `net.isIP`。

winget-source: add V2 index package to sync

---

winget-source/package-lock.json
winget-source/package.json
winget-source/sync-repo.js
winget-source/utilities.js

- 解析 WinGet V2 索引数据库；
- 支持同步新增的 `packages` 信息；
- 增加鲁棒性。

winget-source: sync metadata using V2 index

---

freebsd-pkg/sync.sh

See also https://wiki.freebsd.org/PkgBase

freebsd-pkg: Add PkgBase

---

freebsd-pkg/sync.sh

freebsd-pkg: get channel list before fetching packagesite.txz

---

ghcup/ghcupsync.hs

solution for https://github.com/ustclug/mirrorhelp/pull/271

ghcup: add latest file for each channel

---

README.md
flatpak/.gitignore
flatpak/Dockerfile
flatpak/sync.py
flatpak/sync.sh

A simple script to sync flatpak ostree metadata, delta* or objects not included.
> summary.idx, summaries/ 和 config 由同步程序定时同步处理，objects/ 由缓存管理程序处理，delta*/ 返回 404（不提供增量同步支持）
TODO:

flatpak: Add
